# Generated by Django 6.0.1 on 2026-01-16 05:18

import apps.blogs.upload_paths
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import markdownx.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name (will be translated)', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name (auto-generated)', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Brief description of this category', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Blog post title (will be translated)', max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated)', max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, help_text='Brief description for list view and SEO (will be translated)', verbose_name='Summary')),
                ('content', markdownx.models.MarkdownxField(help_text='Main blog post content in Markdown format (will be translated)', verbose_name='Content')),
                ('featured_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Main image displayed in blog list (auto-processed to 1200x630 WEBP)', max_length=255, null=True, upload_to=apps.blogs.upload_paths.blog_featured_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif'])], verbose_name='Featured Image')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max, defaults to post title if empty)', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 chars max, defaults to summary if empty)', max_length=160, verbose_name='Meta Description')),
                ('og_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image for social media sharing (auto-processed to 1200x630 WEBP)', max_length=255, null=True, upload_to=apps.blogs.upload_paths.blog_og_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif'])], verbose_name='Open Graph Image')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if this post was originally published elsewhere', verbose_name='Canonical URL')),
                ('published', models.BooleanField(default=False, help_text='Check to publish this post publicly', verbose_name='Published')),
                ('date', models.DateField(blank=True, help_text='Date to display as publication date', null=True, verbose_name='Publication Date')),
                ('preview_token', models.UUIDField(blank=True, editable=False, help_text='Secret token for previewing unpublished posts', null=True, unique=True, verbose_name='Preview Token')),
                ('author', models.ForeignKey(help_text='Only staff members can author blog posts', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, help_text='Select categories for this post', related_name='blogs', to='blogs.blogcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', '-created_at'], name='blogs_blog_date_f567d7_idx'), models.Index(fields=['slug'], name='blogs_blog_slug_d0bba8_idx'), models.Index(fields=['published', '-date'], name='blogs_blog_publish_d029bd_idx'), models.Index(fields=['author'], name='blogs_blog_author__166d94_idx')],
            },
        ),
    ]
