# Generated by Django 5.2.7 on 2025-11-10 07:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Full language name, e.g., 'English', 'Spanish'", max_length=100, unique=True, verbose_name='Language Name')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish (Spain)')], help_text="ISO language code, e.g., 'en', 'es'", max_length=10, unique=True, verbose_name='Language Code')),
                ('country', models.CharField(blank=True, help_text="Country or region, e.g., 'Spain' for Spanish (Spain)", max_length=100, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
    ]
