# Generated by Django 5.2.7 on 2025-10-30 03:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0002_2_10'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Books', 'Toys')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL slug for category filtering', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description for category pages')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show category in navigation/filters')),
            ],
            options={
                'verbose_name': 'Shop Category',
                'verbose_name_plural': 'Shop Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_out', models.BooleanField(default=False, help_text='True when basket has been converted to an order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(blank=True, help_text='Original basket that created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.basket')),
                ('session', models.OneToOneField(help_text='Checkout Session - contains line_items, amounts, payment_intent', on_delete=django.db.models.deletion.PROTECT, related_name='shop_order', to='djstripe.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(db_index=True, help_text='Stripe Product ID (matches djstripe.Product.id)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Display name (can differ from Stripe product name)', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug for product detail page', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Rich product description for detail page')),
                ('is_new', models.BooleanField(default=False, help_text="Show 'NEW' badge in UI")),
                ('is_popular', models.BooleanField(default=False, help_text="Show 'POPULAR' badge in UI")),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within category (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show product in shop (can hide without deleting)')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.shopcategory')),
            ],
            options={
                'verbose_name': 'Shop Product',
                'verbose_name_plural': 'Shop Products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Product image (uploaded via admin)', upload_to='shop/products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shopproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.basket')),
                ('product', models.ForeignKey(help_text='Stripe Product (for pricing and checkout)', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='djstripe.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('basket', 'product')},
            },
        ),
    ]
