# Generated by Django 5.2.7 on 2025-10-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_customer_customuser_subscription'),
        ('djstripe', '0002_2_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object (cached for performance)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
