# Generated by Django 5.2.7 on 2025-11-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile picture (max 8MB)', null=True, upload_to='profiles/%Y/%m/'),
        ),
    ]
